add lecture05
sakinemoto/RaisetechAWS pull request #6
Opened 2023-08-29 18:31 UTC by sakinemoto

第5回講座の課題を提出いたします。ご確認お願いいたします。

2023-08-30 00:19 UTC, MasatoshiMizumoto requested changes
内容としてはOKなんですが記法の指摘をしたので、対応お願いします！！

2023-08-30 00:19 UTC, MasatoshiMizumoto commented on lecture05.md
> +     ```
番号つきリストの下にすぐ書いてしまってるので正しく認識されてないですね！

2023-08-30 00:19 UTC, MasatoshiMizumoto commented on lecture05.md
> +<img width="1253" alt="pumaで起動" src="https://github.com/sakinemoto/RaisetechAWS/assets/88425419/8fcb1e3e-9765-4e29-88c4-42097fe77070">
MarkdownのメリットってHTMLタグを書かずにできることなんで、この記法じゃない形でお願いしたいです！
画像ファイルもpushで対応してください！

2023-09-03 07:14 UTC, sakinemoto commented
修正しました、お手隙にご確認のほどよろしくお願いいたします。

2023-09-03 07:19 UTC, MasatoshiMizumoto requested changes
`.DS_Store`がpushされてしまっているので、今後含まれないように対策をして削除いただきたいです！

2023-09-03 07:57 UTC, sakinemoto commented
git ignoreファイルに　DS_Sotreを追記することで対策・削除いたしました。
ご確認お願いいたします。

2023-09-03 08:06 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2023-09-03 08:06 UTC, MasatoshiMizumoto commented on lecture05.md
> +   ```config.active.storage.service=amazon```
これのほうが良いですかねー。
```suggestion
   `config.active.storage.service=amazon`
```

2023-09-03 08:06 UTC, MasatoshiMizumoto commented on img/.DS_Store
これも不要なファイルですね！

2023-09-03 11:46 UTC, sakinemoto commented
ありがとうございます！
gitignoreの見落としもご指摘ありがとうございます！

2023-09-03 11:57 UTC, MasatoshiMizumoto requested changes
後出しですいませんが、もう少し修正お付き合いください！
よろしくおねがいします！
https://github.com/sakinemoto/RaisetechAWS/pull/6/files#diff-6a10efad6ede77da1a8048f4198bce15e400bd9003b6a3bf5449a3da045895a1

2023-09-03 11:57 UTC, MasatoshiMizumoto commented on lecture05.md
> +   ```json
yamlですね！
```suggestion

   ```yaml
```

2023-09-03 11:57 UTC, MasatoshiMizumoto commented on lecture05.md
> +6. credential.ymlの編集
GitHubの画面で文字種別が正しく認識されてないので適宜改行入れましょうか。
`Files Changed`画面で赤くなってる部分がそれなので出なくなるまで修正してください！
```suggestion

6. credential.ymlの編集 
```

2023-09-05 01:35 UTC, MasatoshiMizumoto requested changes
Markdownは綺麗になりましたね！
残り1点ご対応お願いします！！

2023-09-05 01:35 UTC, MasatoshiMizumoto commented on img/.DS_Store
`.gitignore`に追加はしてもらっているのですが、消すのは別操作でやらないといけないので、こちらお願いします！！

2023-09-07 16:37 UTC, MasatoshiMizumoto approved these changes
LGTM!
![LGTM](https://image.lgtmoon.dev/221595)

2023-10-08 19:35 UTC, merged